### ISSUE TITLE
Home Pages revision

### ISSUE THREAD

**Issue by techarendra** [Syrinx/Syrinx.github.io#7]
Please refer the below specification to validate
https://github.com/Syrinx/Syrinx.github.io/files/303437/SYRINX-WEBSITE-RECAP_7June2016.docx

Pending issues:
1) Homepage header text alignment
2) Home page navigation menu alignment (responsive) and placing a auto expandable search icon.
3) Scrolling blog title animation to get top 5 recent blog items and transition from right to left.
4) Xamarin page styles should be consistent with other pages.

**Comment by SyrinxCC** [comment]
Do you need my approval prior to deploying? I couldn't see the changes on the site. Can you ring me when you have a minute 617 571 2419. Thank you, Nicole


[Syrinx Consulting Corporation]<http://www.syrinx.com/>

Nicole Vale / VP Marketing & PR
nvale@syrinx.com<mailto:nvale@syrinx.com>

Syrinx Consulting Corporation
781-487-7800 ext. 107
www.syrinx.com<http://www.syrinx.com/>

[Twitter]<https://twitter.com/syrinxco> [Facebook] <https://www.facebook.com/SyrinxConsulting>  [LinkedIn] <https://www.linkedin.com/company/syrinx-consulting-corporation>  [Stack Overflow] <http://careers.stackoverflow.com/company/syrinx-consulting>  [Wordpress] <http://blogs.syrinx.com/>

This e-mail message may contain confidential or legally privileged information and is intended only for the use of the intended recipient(s). Any unauthorized disclosure, dissemination, distribution, copying or the taking of any action in reliance on the information herein is prohibited. E-mails are not secure and cannot be guaranteed to be error free as they can be intercepted, amended, or contain viruses. Anyone who communicates with us by e-mail is deemed to have accepted these risks. Company Name is not responsible for errors or omissions in this message and denies any responsibility for any damage arising from the use of e-mail. Any opinion and other statement contained in this message and any attachment are solely those of the author and do not necessarily represent those of the company.


________________________________

**Comment by SyrinxCC** [comment]
Re Hareendra's note above... I believe the mock-up is complete in the coding, we have a few adjustments here that Richard can probably complete... Richard, please let Jarrod or I know any questions here. This will be priority #3 after Jobs / Dice listing and Xamarin Landing Page. Thanks

**Comment by richardrissanen** [comment]
> 1) Homepage header text alignment
> 2) Home page navigation menu alignment (responsive) and placing a auto expandable search icon.
> 3) Scrolling blog title animation to get top 5 recent blog items and transition from right to left.
> 4) Xamarin page styles should be consistent with other pages.

##Several questions:

- How is the homepage header text supposed to be aligned? 
- Is the homepage header text supposed to change?
- If yes to above question, change to what?
- Is the homepage navigation menu not already responsive and aligned?
- What is the purpose of the search? What would a customer search for on our site outside of the blog archive? This seems like adding a search for the sake of having one.
- Does anyone else think that adding the blog posts to the front page detracts from the narrative / call to action?

##Comment:

Xamarin page styles have been fixed within the xamarin branch.

**Comment by richardrissanen** [comment]
Blocked until questions are answered.

**Comment by jarrodtaylor** [comment]
The header text doesn't have anything to balance it out so it'll have to be centered. Preferably at 1/2 to 2/3 the width of the normal content. The trick will be finding a way to give it some focus. Without the normal billboard header, there's no "first focus" element on the page.

Until there is something to change the text to, no, it shouldn't change.

For the nav, the idea is to have the nav links left aligned (next to the logo), but then switch back to the way they are now when on a phone (on the right, the dropdown thingy).

The purpose of the search, from an internal perspective and not counting the blog search, I think is to know what people are looking for when they come to the site (seems like our analytics should tell us this anyway). For a visitor, if they arrive from a Google search, marketing material, or word-of-mouth and are looking for something specific, search would be a way to find it. Sort of a back up in case the nav doesn't work. As for the underlying problem, the solution would be to scale back the content until the story and message are unmistakable.

On a more technical level, a site-wide search may require an index to be generated during the build process. It's probably a day's worth of work by itself.

As for putting the blog posts on the home page - yes, I agree. If they're on that page, I'd rather see them under a "Recent Articles" section underneath the main message, and have the recent 3 on there all at once.

A lot of these issues stem from us pushing a message directly instead of through a story - it means we have to be very careful not to lose focus.

---

Site note - If this thread keeps growing, we should consider splitting it by issue.

**Comment by SyrinxCC** [comment]
Tony and I have a meeting today to discuss and resolve
